# Generated by Django 5.0.1 on 2024-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0004_book_average_rating_rating"),
    ]

    operations = [
        #migrations.AddField(
        #    model_name="mainmenu",
         #   name="display_order",
          #  field=models.IntegerField(blank=True, null=True),
        #),
    ]
